/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kaisquare.analytics.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum VcaState implements org.apache.thrift.TEnum {
  WAITING(0),
  RUNNING(1),
  ERROR(2),
  EXITED(3),
  CMDERR(4);

  private final int value;

  private VcaState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static VcaState findByValue(int value) { 
    switch (value) {
      case 0:
        return WAITING;
      case 1:
        return RUNNING;
      case 2:
        return ERROR;
      case 3:
        return EXITED;
      case 4:
        return CMDERR;
      default:
        return null;
    }
  }
}
